import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider extends ChangeNotifier {
  String _currentLanguage = 'fr';

  String get currentLanguage => _currentLanguage;
  bool get isRTL => _currentLanguage == 'ar';

  LanguageProvider() {
    _loadLanguageFromPrefs();
  }

  void _loadLanguageFromPrefs() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLanguage = prefs.getString('languageCode') ?? 'fr';
    notifyListeners();
  }

  void setLanguage(String langCode) async {
    if (_currentLanguage != langCode) {
      _currentLanguage = langCode;
      notifyListeners();
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString('languageCode', langCode);
    }
  }

  String translate(String key) {
    return _translations[_currentLanguage]?[key] ??
        _translations['fr']?[key] ??
        key;
  }

  static const Map<String, Map<String, String>> _translations = {
    'fr': {
      'brandName': 'Le Crispy',
      'brandSubtitle': 'Fast Food Gourmet & Fine Dining',
      'navHome': 'Accueil',
      'navMenu': 'Le Menu',
      'navHealthy': 'Healthy & Gym',
      'navReviews': 'Avis Clients',
      'navProfile': 'Mon Profil',
      'navDashboard': 'Commandes',
      'welcomeTitle': 'Une Expérience Gastronomique Fast-Food Incroyable',
      'welcomeSubtitle': 'La fusion entre le prestige de la haute cuisine et la gourmandise du burger.',
      'welcomeExplore': 'Découvrir la Carte',
      'welcomeSkip': 'Accéder au Menu',
      'heroTitlePrefix': 'Le Fast-Food',
      'heroTitleGold': 'Haute Couture',
      'heroSubtitle': 'Saveurs d\'exception, ingrédients biologiques d\'origine contrôlée, viandes maturées et dorure d\'art culinaire.',
      'heroOrderCta': 'Commander Maintenant',
      'heroBookTableCta': 'Scanner QR Table',
      'atout1Title': 'Livraison Haute Précision',
      'atout1Desc': 'Livré en boîte isotherme dorée sous 30 minutes avec température optimale garantie.',
      'atout2Title': 'Viandes Maturées 28 Jours',
      'atout2Desc': 'Boeuf Wagyu et Black Angus d\'exception, grillé à la flamme sur pierre de lava.',
      'atout3Title': 'Fait Maison & Bio',
      'atout3Desc': 'Pains briochés pétris quotidiennement par nos maîtres boulangers.',
      'qrTitle': 'Menu Numérique & Scan à Table',
      'qrSubtitle': 'Vous êtes installé à table ? Scannez le QR Code sur votre table pour commander.',
      'qrScanBtn': 'Scanner un QR Code',
      'qrScanSimulateBtn': 'Simuler Table N° 07',
      'menuTitle': 'Notre Carte Prestige',
      'menuSubtitle': 'Tous nos plats sont préparés à la minute par notre brigade avec des produits d\'exception.',
      'allCategories': 'Toutes les Catégories',
      'searchPlaceholder': 'Rechercher un plat, un ingrédient...',
      'addToCart': 'Ajouter au Panier',
      'prepTime': 'Temps de prép.',
      'mins': 'min',
      'spiceLevel': 'Intensité épicée',
      'healthyTitle': 'Espace Healthy, Gym & Diététique',
      'healthySubtitle': 'Des compositions calculées avec précision pour les athlètes et diètes sportives.',
      'maxCalories': 'Calories max',
      'minProtein': 'Protéines min',
      'maxCarbs': 'Glucides max',
      'dietType': 'Régime Spécifique',
      'allDiets': 'Tous les régimes',
      'dietKeto': 'Kéto / Low Carb',
      'dietHighProtein': 'Riche en Protéines',
      'dietDiabetic': 'Adapté Diabétique',
      'dietLowFat': 'Faible en Gras',
      'dietVegetarian': 'Végétarien',
      'dietGlutenFree': 'Sans Gluten',
      'nutritionFacts': 'Valeurs Nutritionnelles',
      'protein': 'Protéines',
      'carbs': 'Glucides',
      'fat': 'Lipides',
      'calories': 'Calories',
      'surPlace': 'Sur Place',
      'aEmporter': 'À Emporter',
      'livraison': 'Livraison',
      'selectServiceMode': 'Choisissez le mode de service',
      'tableNumberLabel': 'Numéro de Table',
      'tablePlaceholder': 'Ex: Table 04',
      'deliveryAddressLabel': 'Adresse de livraison',
      'cartTitle': 'Votre Panier Prestige',
      'cartEmpty': 'Votre panier est actuellement vide.',
      'subtotal': 'Sous-total',
      'deliveryFee': 'Frais de livraison',
      'total': 'Total',
      'checkoutBtn': 'Procéder au Paiement',
      'payNow': 'Payer & Valider',
      'orderConfirmed': 'Commande Confirmée !',
      'reviewsTitle': 'Avis Clients & Expérience',
      'addReview': 'Laisser un Avis',
      'chatHeaderTitle': 'Chef IA — Concierge Culinaire',
      'chatHeaderStatus': 'En ligne • Conseils personnalisés',
      'chatPlaceholder': 'Posez votre question culinaire...',
      'chatWelcomeMsg': 'Bonjour ! Je suis votre Concierge IA. Que souhaitez-vous déguster aujourd\'hui ?',
      'profileTitle': 'Mon Compte Prestige',
      'loginTitle': 'Connexion Compte Client',
      'registerTitle': 'Créer un Compte',
      'emailLabel': 'Adresse Email',
      'passwordLabel': 'Mot de Passe',
      'nameLabel': 'Nom Complet',
      'phoneLabel': 'Numéro de Téléphone',
      'loginBtn': 'Se Connecter',
      'registerBtn': 'S\'inscrire',
      'logout': 'Déconnexion',
    },
    'ar': {
      'brandName': 'Le Crispy',
      'brandSubtitle': 'مطعم الوجبات السريعة المقرمشة والفاخرة',
      'navHome': 'الرئيسية',
      'navMenu': 'القائمة',
      'navHealthy': 'صحي ورياضة',
      'navReviews': 'الآراء',
      'navProfile': 'حسابي',
      'navDashboard': 'الطلبات',
      'welcomeTitle': 'تجربة طعام فاخر لا تُنسى',
      'welcomeSubtitle': 'الاندماج بين فخامة الطهي الرفيع ولذة البرجر الحرفي.',
      'welcomeExplore': 'استكشف القائمة',
      'welcomeSkip': 'الدخول للقائمة',
      'heroTitlePrefix': 'الوجبات السريعة',
      'heroTitleGold': 'الراقية والفاخرة',
      'heroSubtitle': 'نكهات استثنائية، مكونات عضوية موثوقة، لحوم معتقة ولمسات ذهبية فاخرة.',
      'heroOrderCta': 'اطلب الآن',
      'heroBookTableCta': 'مسح QR الطاولة',
      'atout1Title': 'توصيل عالي الدقة',
      'atout1Desc': 'يتم التوصيل في صناديق حرارية ذهبية خلال 30 دقيقة.',
      'atout2Title': 'لحوم معتقة 28 يوماً',
      'atout2Desc': 'لحم واغيو وبلاك أنجوس فاخر، مشوي على الفحم.',
      'atout3Title': 'محضر يدوياً وعضوي',
      'atout3Desc': 'خبز بريوش طازج يومياً من خُبزائنا الحرفيين.',
      'qrTitle': 'القائمة الرقمية والمسح من الطاولة',
      'qrSubtitle': 'هل أنت في الطاولة الآن؟ امسح رمز QR الموجود على الطاولة للطلب.',
      'qrScanBtn': 'مسح رمز QR',
      'qrScanSimulateBtn': 'محاكاة الطاولة 07',
      'menuTitle': 'قائمتنا الفاخرة',
      'menuSubtitle': 'جميع أطباقنا تُحضر فورياً بأيدي طهاتنا من مكونات نادرة.',
      'allCategories': 'جميع الفئات',
      'searchPlaceholder': 'ابحث عن طبق أو مكون...',
      'addToCart': 'إضافة للسلة',
      'prepTime': 'وقت التحضير',
      'mins': 'دقيقة',
      'spiceLevel': 'درجة الحرارة',
      'healthyTitle': 'قسم الصحة والرياضة',
      'healthySubtitle': 'قيم غذائية محسوبة بدقة للرياضيين والأنظمة الغذائية.',
      'maxCalories': 'أقصى سعرات',
      'minProtein': 'أدنى بروتين',
      'maxCarbs': 'أقصى كربوهيدرات',
      'dietType': 'نظام غذائي خاص',
      'allDiets': 'جميع الأنظمة',
      'dietKeto': 'كيتو / كربوهيدرات منخفضة',
      'dietHighProtein': 'غني بالبروتين',
      'dietDiabetic': 'مناسب للسكري',
      'dietLowFat': 'قليل الدهون',
      'dietVegetarian': 'نباتي',
      'dietGlutenFree': 'خالي من الجلوتين',
      'nutritionFacts': 'القيمة الغذائية',
      'protein': 'بروتين',
      'carbs': 'كربوهيدرات',
      'fat': 'دهون',
      'calories': 'سعرات',
      'surPlace': 'في المطعم',
      'aEmporter': 'استلام سفري',
      'livraison': 'توصيل للمنزل',
      'selectServiceMode': 'اختر طريقة الخدمة',
      'tableNumberLabel': 'رقم الطاولة',
      'tablePlaceholder': 'مثال: طاولة 04',
      'deliveryAddressLabel': 'عنوان التوصيل',
      'cartTitle': 'سلة المشتريات الفاخرة',
      'cartEmpty': 'سلتك فارغة حالياً.',
      'subtotal': 'المجموع الفرعي',
      'deliveryFee': 'رسوم التوصيل',
      'total': 'الإجمالي',
      'checkoutBtn': 'إتمام الدفع والطلب',
      'payNow': 'تأكيد ودفع',
      'orderConfirmed': 'تم تأكيد الطلب بنجاح !',
      'reviewsTitle': 'آراء العملاء والتقييمات',
      'addReview': 'إضافة تقييم',
      'chatHeaderTitle': 'الطاهي الذكي — المستشار الغذائي',
      'chatHeaderStatus': 'متصل • نصائح مخصصة',
      'chatPlaceholder': 'اطرح سؤالك على الطاهي...',
      'chatWelcomeMsg': 'مرحباً! أنا المستشار الذكي. ماذا تحب أن تتذوق اليوم؟',
      'profileTitle': 'حسابي الفاخر',
      'loginTitle': 'تسجيل الدخول',
      'registerTitle': 'إنشاء حساب جديد',
      'emailLabel': 'البريد الإلكتروني',
      'passwordLabel': 'كلمة المرور',
      'nameLabel': 'الاسم الكامل',
      'phoneLabel': 'رقم الهاتف',
      'loginBtn': 'دخول',
      'registerBtn': 'تسجيل',
      'logout': 'تسجيل الخروج',
    },
    'en': {
      'brandName': 'Le Crispy',
      'brandSubtitle': 'Fast Food Gourmet & Fine Dining',
      'navHome': 'Home',
      'navMenu': 'Menu',
      'navHealthy': 'Healthy & Gym',
      'navReviews': 'Reviews',
      'navProfile': 'Profile',
      'navDashboard': 'Orders',
      'welcomeTitle': 'An Incredible Fast-Food Gourmet Experience',
      'welcomeSubtitle': 'The fusion between high gastronomy and burger indulgence.',
      'welcomeExplore': 'Explore Menu',
      'welcomeSkip': 'Skip to Menu',
      'heroTitlePrefix': 'The Fast-Food',
      'heroTitleGold': 'Haute Couture',
      'heroSubtitle': 'Exceptional flavors, organic certified ingredients, 28-day aged meats.',
      'heroOrderCta': 'Order Now',
      'heroBookTableCta': 'Scan Table QR',
      'atout1Title': 'High Precision Delivery',
      'atout1Desc': 'Delivered in golden isothermal boxes within 30 minutes.',
      'atout2Title': '28-Day Aged Meats',
      'atout2Desc': 'Wagyu and Black Angus beef, flame grilled over lava stones.',
      'atout3Title': 'Organic & Homemade',
      'atout3Desc': 'Brioche buns freshly kneaded daily by our master bakers.',
      'qrTitle': 'Digital Menu & Table Scan',
      'qrSubtitle': 'Seated at a table? Scan your table\'s QR code to order directly.',
      'qrScanBtn': 'Scan QR Code',
      'qrScanSimulateBtn': 'Simulate Table #07',
      'menuTitle': 'Our Prestige Menu',
      'menuSubtitle': 'All dishes are cooked fresh to order by our kitchen team.',
      'allCategories': 'All Categories',
      'searchPlaceholder': 'Search a dish, ingredient...',
      'addToCart': 'Add to Cart',
      'prepTime': 'Prep time',
      'mins': 'mins',
      'spiceLevel': 'Spice level',
      'healthyTitle': 'Healthy, Gym & Fitness',
      'healthySubtitle': 'Calculated macros for athletes and fitness diets.',
      'maxCalories': 'Max calories',
      'minProtein': 'Min protein',
      'maxCarbs': 'Max carbs',
      'dietType': 'Specific Diet',
      'allDiets': 'All diets',
      'dietKeto': 'Keto / Low Carb',
      'dietHighProtein': 'High Protein',
      'dietDiabetic': 'Diabetic Friendly',
      'dietLowFat': 'Low Fat',
      'dietVegetarian': 'Vegetarian',
      'dietGlutenFree': 'Gluten Free',
      'nutritionFacts': 'Nutrition Facts',
      'protein': 'Protein',
      'carbs': 'Carbs',
      'fat': 'Fat',
      'calories': 'Calories',
      'surPlace': 'Dine-In',
      'aEmporter': 'Takeaway',
      'livraison': 'Home Delivery',
      'selectServiceMode': 'Select Service Mode',
      'tableNumberLabel': 'Table Number',
      'tablePlaceholder': 'e.g. Table 04',
      'deliveryAddressLabel': 'Delivery Address',
      'cartTitle': 'Your Prestige Cart',
      'cartEmpty': 'Your cart is currently empty.',
      'subtotal': 'Subtotal',
      'deliveryFee': 'Delivery fee',
      'total': 'Total',
      'checkoutBtn': 'Proceed to Checkout',
      'payNow': 'Pay & Confirm',
      'orderConfirmed': 'Order Confirmed!',
      'reviewsTitle': 'Customer Reviews',
      'addReview': 'Leave a Review',
      'chatHeaderTitle': 'AI Chef — Culinary Concierge',
      'chatHeaderStatus': 'Online • Personalized suggestions',
      'chatPlaceholder': 'Ask our AI Chef...',
      'chatWelcomeMsg': 'Hello! I am your AI Culinary Concierge. What would you like to taste today?',
      'profileTitle': 'My Prestige Account',
      'loginTitle': 'Client Login',
      'registerTitle': 'Create Account',
      'emailLabel': 'Email Address',
      'passwordLabel': 'Password',
      'nameLabel': 'Full Name',
      'phoneLabel': 'Phone Number',
      'loginBtn': 'Login',
      'registerBtn': 'Register',
      'logout': 'Logout',
    }
  };
}
